/**
 * Which SYSCOHADA account each money category and each posting role uses by default (pure). A
 * company may override any of them (Company.accountMap: { "category:opex-gas": "6053", "role:CASH":
 * "5711" }); the overrides are checked against its chart when saved.
 */

export const ROLE_ACCOUNTS = {
  CASH: "5711", // a department's cash drawer
  MOMO: "552",
  BANK_TRANSFER: "5211",
  OTHER: "513", // cheques, cards … to collect
  BOSS_CASH: "5712", // cash handed to the Boss
  CUSTOMERS: "411",
  CUSTOMER_ADVANCES: "4191", // credit balances of 411, shown apart on the balance sheet
  SUPPLIERS: "401",
  DEPOSITS_HELD: "165",
  DISCOUNTS: "7019",
  BAD_DEBTS: "651",
  OPENING_EQUITY: "121", // balances that existed before the app (old debts, opening wizard)
  SUSPENSE: "4711",
  SALES_MEALS: "702",
  EVENTS: "7061",
  NIGHTS: "7062",
  RENTAL: "7063",
  OFFICE_RENT: "7064",
  SERVICES: "706", // job tickets (pressing, car wash, jobs)
  GOODS_STOCK: "311",
  STOCK_CHANGE: "6031",
  RAW_STOCK: "321", // raw materials and farm inputs
  RAW_CHANGE: "6032",
  FINISHED_STOCK: "361", // finished products made (production) and farm produce
  FINISHED_CHANGE: "734", // variation of finished products (income side)
  PACKAGING_PAID: "4094", // deposits on crates paid to suppliers (to get back)
  PACKAGING_RECEIVED: "4194", // deposits received from customers (to give back)
  TENANT_CHARGES: "7065",
  DAMAGES: "7066",
  KEPT: "7581", // kept on cancellations, penalties
  ASSET_LOSS: "6581",
  FURNITURE: "244", // furniture and equipment of halls and apartments
  RENTAL_EQUIPMENT: "2446", // items rented out
  DEPRECIATION: "681",
  ACC_DEPRECIATION: "2844",
  ASSET_SOLD_BOOK: "812",
  ASSET_SOLD_PROCEEDS: "822",
  ASSET_SALE_RECEIVABLE: "485",
  VAT_COLLECTED: "4432",
  VAT_COLLECTED_GOODS: "4431",
  VAT_DEDUCTIBLE: "4454",
  VAT_DEDUCTIBLE_GOODS: "4452",
  VAT_DEDUCTIBLE_ASSETS: "4451",
  VAT_PAYABLE: "4441",
  VAT_CREDIT: "4449",
  RESULT_PROFIT: "131",
  RESULT_LOSS: "139",
};

export const ROLE_LABELS = {
  CASH: "Department cash drawers",
  MOMO: "Mobile Money",
  BANK_TRANSFER: "Bank",
  OTHER: "Other payment methods (cheques, cards)",
  BOSS_CASH: "Cash handed to the Boss",
  CUSTOMERS: "Customers and tenants",
  SUPPLIERS: "Suppliers",
  DEPOSITS_HELD: "Deposits held (cautions)",
  DISCOUNTS: "Discounts and debts forgiven",
  BAD_DEBTS: "Debts written off",
  OPENING_EQUITY: "Opening balances",
  SALES_MEALS: "Restaurant sales",
  EVENTS: "Events held (halls)",
  NIGHTS: "Nights (guest house)",
  RENTAL: "Event rentals",
  OFFICE_RENT: "Office rent",
  SERVICES: "Job tickets (pressing, car wash, jobs)",
  GOODS_STOCK: "Goods in stock",
  STOCK_CHANGE: "Change in stock of goods",
  RAW_STOCK: "Raw materials and farm inputs in stock",
  RAW_CHANGE: "Change in stock of raw materials",
  FINISHED_STOCK: "Finished products in stock",
  FINISHED_CHANGE: "Change in stock of finished products",
  PACKAGING_PAID: "Crate deposits paid to suppliers",
  PACKAGING_RECEIVED: "Bottle deposits received from customers",
  TENANT_CHARGES: "Charges billed to tenants",
  DAMAGES: "Damages charged",
  KEPT: "Kept on cancellations",
  ASSET_LOSS: "Assets lost",
  FURNITURE: "Furniture and equipment",
  RENTAL_EQUIPMENT: "Rental items and equipment",
  DEPRECIATION: "Depreciation",
  ACC_DEPRECIATION: "Accumulated depreciation",
  VAT_COLLECTED: "VAT collected",
  VAT_DEDUCTIBLE: "Deductible VAT",
  VAT_PAYABLE: "VAT to pay",
  VAT_CREDIT: "VAT credit",
};

/** Default account of each money category (data/categories.js and the categories set by the app). */
export const CATEGORY_ACCOUNTS = {
  // Income
  "sale-food": "702",
  "rent-space": "7073",
  "rent-room": "7073",
  "rent-equipment": "7073",
  "income-event-fee": "7078",
  "venue-extra-services": "7078",
  "venue-other-rental": "7073",
  "income-catering": "7078",
  "income-refund": "758",
  "stay-extra-services": "7078",
  "rental-walk-in": "7063",
  "rental-item-sold": "822",
  "property-parking": "7073",
  "property-short-use": "7073",
  "property-penalties": "7581",
  "shop-services": "7078",
  "bar-hall-hire": "7073",
  "bar-entry-fees": "7078",
  "pressing-alterations": "706",
  "carwash-products": "701",
  "sale-goods": "701",
  "sale-drinks": "701",
  "sale-other": "701",
  "sale-production": "702",
  "sale-farm": "702",
  "membership-sale": "706",
  "purchase-raw": "602",
  "purchase-farm-inputs": "602",
  "production-custom-orders": "706",
  "farm-manure": "7078",
  "farm-subsidy": "758",
  "salon-products": "701",
  "salon-day-pass": "706",
  "production-energy": "6053",
  "production-packaging": "608",
  "production-machines": "624",
  "production-labour": "661",
  "farm-young-animals": "602",
  "farm-feed": "602",
  "farm-vet": "604",
  "farm-seeds": "602",
  "farm-labour": "661",
  "farm-energy": "6053",
  "farm-equipment": "624",
  "salon-supplies": "604",
  "salon-equipment": "624",
  "salon-staff": "661",
  "income-other": "758",
  // Discounts
  "discount-customer": "7019",
  "discount-promo": "7019",
  "discount-staff": "7019",
  // Purchases
  "purchase-goods": "601",
  "purchase-drinks": "601",
  "purchase-food": "602",
  "purchase-ready": "601",
  "purchase-supplies": "604",
  // Expenses
  "venue-decoration": "604",
  "venue-cleaning": "637",
  "venue-security": "637",
  "venue-event-staff": "637",
  "venue-sound-light": "622",
  "venue-generator": "6053",
  "venue-asset-replacement": "6056",
  "stay-cleaning": "6054",
  "stay-supplies": "604",
  "stay-internet-tv": "628",
  "stay-security": "637",
  "stay-repairs": "624",
  "stay-asset-purchase": "244",
  "rental-fuel": "6053",
  "rental-decoration-materials": "604",
  "rental-storage": "622",
  "rental-packaging": "608",
  "rental-communication": "628",
  "rental-marketing": "627",
  "rental-repairs": "624",
  "rental-stock": "2446",
  "trade-shop-rent": "622",
  "trade-council-tax": "641",
  "bar-ice": "604",
  "bar-music": "638",
  "bar-grill": "602",
  "bar-security": "637",
  "pressing-detergent": "604",
  "pressing-packaging": "608",
  "pressing-machines": "624",
  "pressing-compensation": "6588",
  "carwash-products-used": "604",
  "carwash-equipment": "624",
  "carwash-commission": "637",
  "trade-shrinkage": "6588",
  "opex-gas": "6053",
  "opex-electricity": "6052",
  "opex-water": "6051",
  "opex-transport": "618",
  "opex-wages": "661",
  "opex-cleaning": "6054",
  "opex-repairs": "624",
  "opex-packaging": "608",
  "property-plumbing": "624",
  "property-security": "637",
  "property-painting": "624",
  "property-construction": "624",
  "property-waste": "638",
  "property-admin": "638",
  "property-utilities-paid": "6052",
  "property-maintenance": "624",
  "opex-other": "638",
  "other-expense-taxes": "641",
  "other-expense-bank-fees": "631",
  "other-expense-donations": "6582",
  "other-expense-fines": "6588",
  "other-expense-misc": "6588",
};

/** Fallback by money type when a category has no account (legacy or unknown categories). */
export const TYPE_FALLBACK = {
  SALE: "702",
  RENT_INCOME: "7073",
  OTHER_INCOME: "758",
  DISCOUNT: "7019",
  PURCHASE: "601",
  EXPENSE: "638",
  OTHER_EXPENSE: "6588",
};

/** Builds the account resolver of a company: role(name) and category(id, type). */
export function accountResolver(overrides = {}) {
  const map = overrides && typeof overrides === "object" ? overrides : {};
  return {
    role: (name) => map[`role:${name}`] || ROLE_ACCOUNTS[name],
    category: (id, type) => map[`category:${id}`] || CATEGORY_ACCOUNTS[id] || TYPE_FALLBACK[type] || ROLE_ACCOUNTS.SUSPENSE,
    treasury: (method) => map[`role:${method}`] || ROLE_ACCOUNTS[method] || ROLE_ACCOUNTS.CASH,
  };
}
